### ISSUE TITLE
Inteligentní určení adresy LI?

### ISSUE THREAD

**Issue by malinajan** [kmzbrnoI/uLI-fw#15]

**Comment by petrilakm** [comment]
Netuším jak to dělá RocoMouse, která to také používá.
Mohlo by to fungovat tak, že se chvíli poslouchá sběrnice (zvolil bych 3x celé kolečko všech adres). A nejvyšší adresa, která je bez odpovědi se použije.

Implementace by mokla být tak, že se nejdříve počítadlo adresy nastaví na 31. Pak se 3x čeká na Normal Inquiry od centrály a pokud ani jednou nenásleduje odpověď, tak se adresa použije. Pokud se alespoň v 1 z 3 případů odpověď objeví, tak se počítadlo sníží o 1. A zase se bude čekat na 3x dotaz od centrály.
To by mohlo být spolehlivé a relativně jednoduché na implementaci. Navíc není důležité jak na začátku trvá určení adresy.

**Comment by malinajan** [comment]
To by šlo.
Chci ale vznést otázku, jestli to má vůbec cenu. Specifikace xpressnetu, resp. LI, říká, že LI má pevně určenou adresu. Dřív byla adresa určená nějakými jumpery, teď je v EEPROM. Má podle tebe cenu implementovat výše zmíněný algoritmus? A máme opravdu jistotu, že centrála nedotazuje zařízení, která nejsou na sběrnici? Jak by pak taková zařízení mohla odeslat první zprávu (těsně po připojení), když nejsou adresována?

**Comment by petrilakm** [comment]
Nemá, dal bych tam 29 a možnost ji změnit z PC.

**Comment by petrilakm** [comment]
Centrála musí vše adresovat, protože zařížení nesmí poslat nic bez dotazu. XpressNET je striktně dotazovaná sbernice.

**Comment by malinajan** [comment]
Ok, 29 a možnost ji změnit z PC.
