### ISSUE TITLE
Posílat zprávu do PC, pokud z XpressNETu dojde další zpráva bez korektního ukončení předchozí?

### ISSUE THREAD

**Issue by malinajan** [kmzbrnoI/uLI-fw#16]
Situace: uLI dostává data z centrály, čeká řekněme 5 bytů, přijdou 3 bajty a pak přijde začátek další zprávy. Chybí 2 bajty. V současné době uLI zahodí ony 3 bajty a vesele jede dál. Mám o této situaci nějak informovat PC? (Timeout during data communication with command station?)

**Comment by petrilakm** [comment]
ta chyba 01 02 03 se jmenuje původne:
"Error occurred between the interfaces and the command station"
což bych řekl že vystihuje situaci. 
Další řešení je ty první 3 bajty odignorovat a maximálně jen připočítat 1 do čítače špatných rámců.
Rozhodnutí je asi na tobě, mě obě varianty příjdou dobré.

**Comment by malinajan** [comment]
Ok, pošlu 01 02 03
