### ISSUE TITLE
Simulace Request for acknowledgement

### ISSUE THREAD

**Issue by malinajan** [kmzbrnoI/uLI-fw#17]
Potřebuji donutit centrálu vystal "Request for acknowledgement", abych se ujistil, že uLI správně odpoví. Jak na to?

**Comment by petrilakm** [comment]
V dokumentaci se píše, že tento požadavek se většinou posílá při spatné komunikaci, pak tam je:  "The most likely cause for this is that the received X-Or-byte was not correct." Takže bych zkusil poslat centrále neplatný XOR. Já osobně jsem se stouto zprávou nikdy nestkal.

**Comment by malinajan** [comment]
Zkusil jsem poslat NanoX chybný XOR, neodpověděla "Request for acknowledgement". Možná vyzkoušet s BCZ100?

**Comment by malinajan** [comment]
Ha, teď se mi to (asi náhodou) stalo a moc to nefunguje.
- Centrála opakovaně dotazuje uLI "Request for ACK" a uLI posílá opakovaně do počítače chybu, opravit, poslat jen jednou.
- uLI zřejmě neodpovídá
