### ISSUE TITLE
Co dělat při přetečení bufferu z USB?

### ISSUE THREAD

**Issue by malinajan** [kmzbrnoI/uLI-fw#18]
Smazat celý buffer, nebo jen poslední zprávu? Pokud jen poslední zprávu, po navázání komunikace s centrálou dojde k odeslání všech nabufferovaných zpráv.
Pokud tato situace nastane, uLI pošle do PC "buffer full", o kterémž specifikace říká, že "If the PC receives this message, one should assume that one or more data records were lost. If necessary this information must again be requested by the PC."

**Comment by petrilakm** [comment]
Pokud uLI nemá navázanou komunikaci s centrálou. Tak by se mělo tvářit, že je velikost bufferu 0. Tedy již při první zprávě se odpoví "buffer full". PC program tak ví, že zpráva nikdy do centrály nedorazí. Ono nemá smysl v uLi něco bufferovat, když není centrála na lince.

**Comment by malinajan** [comment]
To dělám.
Mně jde o situaci, kdy komunikace funguje a buffer se zaplní (PC posílá data rychleji, než je uLI schopno posílat centrále). Smazat celý buffer, nebo jen poslední zprávu? Pokud jen poslední zprávu, po navázání komunikace s centrálou dojde k odeslání všech nabufferovaných zpráv.

**Comment by petrilakm** [comment]
Když řešíš situaci, kdy to funguje tak nějak nechápu to navázání komunikace. Každopádně při zaplnění bufferu při provozu bych zahodil jen tu poslední zprávu.

**Comment by malinajan** [comment]
Ok. Asi jsem to issue psal před tím, než jsem nastavoval velikosti bufferu na 0 při výpadku komunikace s centrálou... pardon
