### ISSUE TITLE
Ovládat CTS linku

### ISSUE THREAD

**Issue by malinajan** [kmzbrnoI/uLI-fw#19]
Michale, máš nějaké tutoriály k CTS lince? Já nic nenašel.

**Comment by petrilakm** [comment]
v souboru
usb_function_cdc.c
je funkce
void USBCheckCDCRequest(void)
tak se řeší změna linek z PC do PIC

**Comment by petrilakm** [comment]
Jak jsem kokal tak v tom demu, co jsem tidal se stím nějak nepočítá.
často se to jmenuje "CONTROL_LINE", ale moc nevím jak najít jak se to používá.

**Comment by malinajan** [comment]
Taky jsem našel CONTROL_LINE, ale nenašel jsem, jak to používat. Zkusím se na to podívat...

**Comment by malinajan** [comment]
Podle mě to rozumně nejde:
http://www.microchip.com/forums/m746114.aspx
The notification doesn’t include the state of RS-232’s CTS status signal. Device firmware can still read CTS on a local asynchronous port and take action as needed. For example, if a virtual COM-port device has data to send to a remote device that hasn’t asserted CTS, the virtual COM-port device can store the data in a buffer and wait to transmit.
If the buffer is full, the virtual COM-port device can NAK attempts by the USB host to send more data. When the remote device asserts CTS, the virtual COM-port device can send the buffered data and accept new data from the host. To use CTS in this way, the USB host doesn’t need to know the state of CTS.
If you want to use CTS in an unconventional way, such as having a host application read a switch state on a device, you’re out of luck with the CDC driver unless you can define a vendor-specific command that travels on the same bulk pipes that carry application data.

Tady se píše, že nic takového, jako CTS, v CDC není, že mám prostě zamítnout nová data, když mám plný buffer. Jestli to teda chápu správně. Mám to nějak dál řešit?

**Comment by malinajan** [comment]
... neposílám teda NAK na úrovní USB endpointu, ale na úrovni xpressnetu. Je to podle tebe OK?

**Comment by malinajan** [comment]
Zatím se ukazuje jako nepotřebné, zavírám.
