### ISSUE TITLE
Microchip driver

### ISSUE THREAD

**Issue by malinajan** [kmzbrnoI/uLI-fw#20]
Kde je k sehnání Microchip CDC driver?

**Comment by petrilakm** [comment]
z jedné diskuze:
I suspect that what you are looking for is in the "USB\Tools\USB CDC Serial Demo\inf" folder of the Microchip Application Libraries.

For the installer, release notes and help files look here:
http://www.microchip.com/stellent/idcplg?IdcService=SS_GET_PAGE&nodeId=2680&dDocName=en547784

It's about a 300mb download for the 12K of files you would need to install the Microsoft driver.
