### ISSUE TITLE
LED diody

### ISSUE THREAD

**Issue by petrilakm** [kmzbrnoI/uLI-fw#21]
Jake barvy LED diod dvolit na napájení 12V a mLED_Pwr bych dal zelenou. A nevim co na In a Out ledky. Žlutá dává smysl barvou, ale zase červená je lépe vidět, když krátce blikne.
Rozhodni si, co chceš za barvi na piny RC0 a RC1.

**Comment by malinajan** [comment]
Zelená na pwr zní logicky, další barvy mi k ní ale nevychází...

Co takhle dát žlutou na PWR, zelenou a červenou na IN a OUT a modrou na napájení? Jsem pro to, aby barvy nebyly duplikované, třeba kvůli řešení problémů s případnými zákazníky. "Bliká ta žlutá vpravo nahoře?" vs "Bliká ta žlutá? (je tam jen jedna)"

**Comment by malinajan** [comment]
Na komunikaci (IN, OUT) klidně mohou být obě zelené -- jedna je defaultně zaplá a druhá defaultně vyplá -- tím jsou podle mě dostatečně odlišeny. STATUS bych dal žlutou. Zbývají 2 LED na detekci napájení na vstupu a na XpressNETu. na XN bych kldině nechal červenou (jako je to na prototypu uLI), na vstup bych dal třeba modrou. Pokud máš jiný názor, klidně issue otevři znovu.
