### ISSUE TITLE
Příkaz na vyprázdnění bufferu

### ISSUE THREAD

**Issue by malinajan** [kmzbrnoI/uLI-fw#24]
@petrilakm Má cenu implementovat příkaz na vyprázdnění bufferu USB -> centrála? Mně dává smysl, že bych chtěl buffer vyprázdnit, když mi centrála přestane odpovídat a já chci bez vypínání zařízení rozumně debugovat a zjišťovat co se děje.

**Comment by petrilakm** [comment]
Ahoj,

na debug to asi smysl má určitě. A bylo by tobré pokud třeba 5 sekund 
centrála modul neosloví, aby se to vyprázdnilo samo.

Aby se nestalo, že něco pošleš do Li, pak teprve zapneš centrálu a ejhle 
centrála provede nabufferovaný povel.

MP

Dne 24.5.2016 v 16:00 Jan Horacek napsal(a):

> @petrilakm https://github.com/petrilakm Má cenu implementovat příkaz
> na vyprázdnění bufferu USB -> centrála? Mně dává smysl, že bych chtěl
> buffer vyprázdnit, když mi centrála přestane odpovídat a já chci bez
> vypínání zařízení rozumně debugovat a zjišťovat co se děje.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/kmzbrnoI/uLI-fw/issues/24

---

Tato zpráva byla zkontrolována na viry programem Avast Antivirus.
https://www.avast.com/antivirus

**Comment by malinajan** [comment]
```
Aby se nestalo, že něco pošleš do Li, pak teprve zapneš centrálu a ejhle centrála provede nabufferovaný povel.
```

Tohle se po staru nestane -- před prvním Normal Inquiry od centrály uLI nepřijímá data z USB, může se ale stát, že restartuješ centrálu a pokud se vejdeš do 5 s, uLI nevyhlásí žádnou chybu a odešle nabufferovaná data. To je ale podle mě validní chování.

Pokud centrála neodpoví do 5 s, vyhlásil bych "Command station is no longer providing timeslot" a vyprázdnil buffer, aby se po připojení neodeslala data znovu. Viz otázka v e-mailu.

**Comment by malinajan** [comment]
Pokud centrála modul neosloví, buffery se vyprázdní. Během normální komunikace si věřím v tom, že to mám napsané dobře, a nějaké samoopravné mechanismy zatím implementovat nebudu. Uvidíme po testování.
